services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: local-gitlab
    hostname: localhost
    environment:
      GITLAB_ROOT_PASSWORD: "${GITLAB_ROOT_PASSWORD:-12345678Qaz}"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        puma['worker_processes'] = 0
        sidekiq['concurrency'] = 5
        prometheus_monitoring['enable'] = false
        gitlab_kas['enable'] = false
        registry['enable'] = false
    ports:
      - "8929:8929"
      - "2224:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: "256m"
    restart: unless-stopped

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
